default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: '127.0.0.1'
  username: ''
  password: ''
  database: 'env-auth-dev'

test:
  <<: *default
  host: '127.0.0.1'
  username: ''
  password: ''
  database: 'env-auth-test'
