# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 820797fa58ad269b58ffba0a74ed2f13a62d5166bf6be545283ca2934f53a76fd08ed2d172d17973f2fe59038176eb8ff0eddfd30b66655d7cd9755572ad144c

test:
  secret_key_base: ab77cba439c458a2c1615b61176893831c9b2a4584a26dddeb22ce437672200516cf89b0d17001499b889a373bf119eec8f89191c3d2c6861a6b725d789660d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
